<?php declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;

/** @var ViewModelRegistry $viewModels */
?>

<div x-data="example()" x-init="init" x-on:private-content-loaded.window="load">
    <div>Content</div>
    <button x-on:click="reload">Reload customer data</button>
</div>

<section x-data="myComponent();" @DOMContentLoaded="onDOMContentLoaded()"></section>

<script>
    function example() {
        return {
            init: function() {
                console.log('Current element', this.$el);
            },
            load: function() {
                console.log('Private content loaded');
            },
            reload: function() {
                window.localStorage.setItem('private-content-reload', '');
                window.dispatchEvent(new CustomEvent('reload-customer-section-data'));
            }
        }
    }

    function myComponent() {
        return {
            onDOMContentLoaded() {
                console.log(window.hyva);
            }
        }
    }
</script>



